dist: xenial   # required for Python >= 3.7
language: python

services:
  - docker

python:
  - "3.7"

install:
  - pip install --upgrade pip wheel
  - pip install torch torchvision fastai
  - pip install -e .[test]
  - python setup.py bdist_wheel
  - pip install -e .

jobs:
  include:

    - stage: "unit" # parallel
      name: "Unit Tests"
      script: pytest test/unit

    - stage: "unit" # parallel
      name: "Tox Tests"
      script: tox

    - stage: build-base
      name: "Docker Build the base image"
      env:
        - CUDA_BASE_VER="10.1"
      script: docker build -t pytorch-base:1.1.0-gpu-py3 -f docker/1.1.0/base/Dockerfile.gpu --build-arg CUDA_BASE_VER=${CUDA_BASE_VER} .
