language: python

os: linux
dist: xenial   # required for Python >= 3.7

services:
  - docker

python:
  - "3.7"

env:
  global:
    - CUDA_BASE_VER="10.1"

install:
  - pip install --upgrade pip wheel
  - pip install torch torchvision fastai
  - pip install -e .[test]
  - python setup.py bdist_wheel
  - pip install -e .

jobs:
  include:

    - stage: "unit" # parallel
      name: "Unit Tests"
      script:
        - pytest test/unit

    - stage: "unit" # parallel
      name: "Tox Tests"
      script:
        - tox

    - stage: base-build-push-image
      name: "Docker Build and Push the base image"
      script:
        - ./scripts/base-build-push-image.sh

    - stage: final-build-push-image
      name: "Docker Build and Push the final image"
      script:
        - ./scripts/final-build-push-image.sh
