# Check https://circleci.com/docs/2.0/language-python/ for more details
version: 2.1
jobs:
  base0:
    machine:
      enabled: true
      image: circleci/classic:edge
    working_directory: ~/repo
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "setup.py" }}
            - v1-dependencies-

      - run:
          name: "Upgrade Python"
          command: |
            sudo apt -qyy update
            sudo apt-get install -y --no-install-recommends software-properties-common
            sudo add-apt-repository ppa:deadsnakes/ppa -y
            sudo apt -qyy update
            sudo apt -qyy install --no-install-recommends 'python3.7-dev'
            sudo ln -s -f /usr/bin/python3.7 /usr/bin/python
            python --version
            python --version 2>&1 | grep "3\.7\.3"
            nvcc --version
            curl -O "https://bootstrap.pypa.io/get-pip.py"
            python get-pip.py
            rm get-pip.py
            sudo ln -s -f /usr/local/bin/pip /usr/bin/pip
            ls -lah --color='always' /usr/bin/pip*
            pip --version
            pip --version 2>&1 | grep "python 3\.7"
            cd /opt/circleci/.pyenv/plugins/python-build/../.. && git pull && cd -
            pyenv install 3.7.3
            pyenv global 3.7.3

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip wheel
            pip install torch torchvision fastai
            pip install -e .[test]
            python setup.py bdist_wheel
            pip install -e .

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "setup.py" }}

      # - setup_remote_docker:
      #     docker_layer_caching: true

      # - run:
      #     name: "Set docker daemon to experimental"
      #     command: |
      #       sudo sh -c 'echo '\''DOCKER_OPTS="--experimental=true"'\'' >> /etc/default/docker'
      #       sudo service docker restart

      - run:
          name: "Docker Build and Push the 0 base image"
          environment:
            CUDA_BASE_VER: "10.1"
            CUDA_BASE_VER_NO_DOTS: "101"
          # https://circleci.com/docs/2.0/env-vars/#built-in-environment-variables
          #  export TRAVIS_BUILD_NUMBER="${CIRCLE_BRANCH}-${CIRCLE_BUILD_NUM}"
          command: |
            set -x
            export TRAVIS_BUILD_NUMBER="${CIRCLE_WORKFLOW_ID}"
            ./scripts/build-push-image.sh 0

  base1:
    machine:
      enabled: true
      image: circleci/classic:edge
    working_directory: ~/repo
    resource_class: xlarge
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "setup.py" }}
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip wheel
            pip install torch torchvision fastai
            pip install -e .[test]
            python setup.py bdist_wheel
            pip install -e .

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "setup.py" }}

      # - setup_remote_docker:
      #     docker_layer_caching: true

      # - run:
      #     name: "Set docker daemon to experimental"
      #     command: |
      #       sudo sh -c 'echo '\''DOCKER_OPTS="--experimental=true"'\'' >> /etc/default/docker'
      #       sudo service docker restart

      - run:
          name: "Docker Build and Push the 1 base image"
          environment:
            CUDA_BASE_VER: "10.1"
            CUDA_BASE_VER_NO_DOTS: "101"
          command: |
            set -x
            export TRAVIS_BUILD_NUMBER="${CIRCLE_WORKFLOW_ID}"
            ./scripts/build-push-image.sh 1

  final:
    machine:
      enabled: true
      image: circleci/classic:edge
    working_directory: ~/repo
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "setup.py" }}
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip wheel
            pip install torch torchvision fastai
            pip install -e .[test]
            python setup.py bdist_wheel
            pip install -e .

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "setup.py" }}

      # - setup_remote_docker:
      #     docker_layer_caching: true

      # - run:
      #     name: "Set docker daemon to experimental"
      #     command: |
      #       sudo sh -c 'echo '\''DOCKER_OPTS="--experimental=true"'\'' >> /etc/default/docker'
      #       sudo service docker restart

      - run:
          name: "Docker Build and Push the final image"
          environment:
            CUDA_BASE_VER: "10.1"
            CUDA_BASE_VER_NO_DOTS: "101"
          command: |
            set -x
            export TRAVIS_BUILD_NUMBER="${CIRCLE_WORKFLOW_ID}"
            ./scripts/build-push-image.sh 2

workflows:
  version: 2
  build_and_push:
    jobs:
      - base0
      - base1:
          requires:
            - base0
      - final:
          requires:
            - base1
