# Check https://circleci.com/docs/2.0/language-python/ for more details
version: 2.1
jobs:
  base0:
    machine:
      enabled: true
      image: circleci/classic:edge
    working_directory: ~/repo
    steps:
      - checkout

      - run:
          name: "Docker Build and Push the 0 base image"
          environment:
            CUDA_BASE_VER: "10.1"
            CUDA_BASE_VER_NO_DOTS: "101"
          command: |
            set -xe
            sudo sh -c 'echo '\''DOCKER_OPTS="--experimental=true"'\'' >> /etc/default/docker'
            sudo service docker restart
            export TRAVIS_BUILD_NUMBER="${CIRCLE_WORKFLOW_ID}"
            ./scripts/build-push-image.sh 0

  base1:
    machine:
      enabled: true
      image: circleci/classic:edge
    working_directory: ~/repo
    resource_class: xlarge
    steps:
      - checkout

      - run:
          name: "Docker Build and Push the 1 base image"
          environment:
            CUDA_BASE_VER: "10.1"
            CUDA_BASE_VER_NO_DOTS: "101"
          command: |
            set -xe
            sudo sh -c 'echo '\''DOCKER_OPTS="--experimental=true"'\'' >> /etc/default/docker'
            sudo service docker restart
            export TRAVIS_BUILD_NUMBER="${CIRCLE_WORKFLOW_ID}"
            ./scripts/build-push-image.sh 1

  final:
    machine:
      enabled: true
      image: circleci/classic:edge
    working_directory: ~/repo
    steps:
      - checkout

      - run:
          name: "Docker Build and Push the final image"
          environment:
            CUDA_BASE_VER: "10.1"
            CUDA_BASE_VER_NO_DOTS: "101"
          command: |
            set -xe
            sudo sh -c 'echo '\''DOCKER_OPTS="--experimental=true"'\'' >> /etc/default/docker'
            sudo service docker restart
            export TRAVIS_BUILD_NUMBER="${CIRCLE_WORKFLOW_ID}"
            ./scripts/build-push-image.sh 2

workflows:
  version: 2
  build_and_push:
    jobs:
      - base0
      - base1:
          requires:
            - base0
      - final:
          requires:
            - base1
